name: Daily Commit

on:
  schedule:
    # Runs every day at 07:30 UTC
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run email 23f3001761@ds.study.iitm.ac.in step
        run: echo "Running email test step"

      - name: Make a dummy change
        run: |
          echo "Daily update: $(date)" >> daily-log.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit: $(date)"
          git push
